# @package _global_

# about 1B params with DCLM tokenizer embeddings (& biases)
# Follows GPT2-Large (but with gating)
model:
  d_model: 1280
  num_heads: 16
  num_layers: 36

  use_gating_mlp: True
