# @package _global_

experiment:
  training_dataset:
    name: NUMBER_STAIRCASE
    path: ""
    split: TRAIN
    seq_len: 256
    global_batch_size: 128
  eval_list:
    - dataset:
        name: NUMBER_STAIRCASE
        path: ""
        split: TRAIN
        seq_len: 1
        global_batch_size: 16
      evaluator: AUTOREGRESSIVE_ROLLOUTS

model:
  transformer_type: DISCRETE
  is_causal: True
  num_vocab: 10
