# @package _global_

sharding:
  mesh_axis_names: ["fsdp"]
  data: ["fsdp"]
  wqkv: ["fsdp"]
  wo: [null, null, "fsdp"]
  wup: ["fsdp"]
  wdown: [null, "fsdp"]
  wemb: []
  wunemb: [null, "fsdp"]
  mlp_hidden: []
  res_stream: []
  att_qkv: []
