# @package _global_

# TODO
sharding:
  mesh_axis_names: ["fsdp"]
  data: ["fsdp"]
  wqkv: ["fsdp"]
  wo: ["fsdp"]
  wup: ["fsdp"]
  wdown: [None, "fsdp"]
  mlp_hidden: []
  res_stream: []
  att_qkv: []
